# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'shopat-bio'
primary_region = 'sin'

[build]

[deploy]
release_command = "npm run migrate"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
